name: Docker Image CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zephyr: [2.7.0]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ matrix.zephyr }} --build-arg ZEPHYR_CACHE=$${{ matrix.zephyr }}
